
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-deployment
        image: python-image:latest
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP
        resources:
          requests:
            cpu: "10m"
            memory: "50Mi"
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-deployment
spec:
ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
selector:
  app: nginx

